---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/thrix/workstation
name: workstation
description: Thrix's workstation

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43

modules:
  - type: rpm-ostree
    install:
      - fontawesome-fonts-all
      - mate-polkit
      - nautilus
      - https://gitlab.com/mvadkert/xerox-3020/-/raw/main/xerox-3020-1.0.0-1.x86_64.rpm
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    optfix:
      - google
      - smfp-common

  - type: bling
    install:
      - rpmfusion

  - type: files
    files:
      - source: system
        destination: /

  - type: fonts
    fonts:
      google-fonts:
        - Source Code Pro
      nerd-fonts:
        - FiraCode
        - Iosevka
        - JetBrainsMono

  - type: script@v1
    snippets:
      # Update CA certs
      - update-ca-trust
      # Remove node suspend in wireplumber
      # Seems causing sound dropping out for a brief time on Fedora 41
      - rm -f /usr/share/wireplumber/scripts/node/suspend-node.lua
      # Set timezone to Prague
      - ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime

  - type: systemd
    system:
      enabled:
        - systemd-timesyncd

  - type: default-flatpaks@v2
    configurations:
      - notify: true
        scope: system
        install:
          - com.dropbox.Client
          - com.tomjwatson.Emote
          - com.transmissionbt.Transmission
          - com.yubico.yubioath
          - im.riot.Riot
          - io.podman_desktop.PodmanDesktop
          - org.fedoraproject.MediaWriter
          - org.flameshot.Flameshot
          - org.gimp.GIMP
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
